=== damiencuvillier/codesquale/xml/XSD Schemas/DirectoryFile.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"> 

<!--================================-->
<!-- Definition of simple attribute -->
<!--================================-->
	
<!-- Directory and file attributes -->
<xs:attribute name="name" type="xs:string"/>
<xs:attribute name="descriptionFile" type="xs:string"/>
<xs:attribute name="absolutePath" type="xs:string"/>
<!-- Import attribute -->
<xs:attribute name="value" type="xs:string"/>		
<!-- Class attributes -->
<xs:attribute name="type" type="xs:string"/>
<xs:attribute name="returnType" type="xs:string"/>
<xs:attribute name="package" type="xs:string"/>
<xs:attribute name="modifier" type="xs:string"/>
<xs:attribute name="parentClass" type="xs:string"/>
	
	
<!--#################-->
<!-- Set of elements -->
<!--#################-->

<xs:element name="directorySet">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="dir"  minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
</xs:element>	
	
<xs:element name="importSet">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="import" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
	
<xs:element name="attributeSet">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="attribute" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="parameterSet">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />	
		</xs:sequence>
	</xs:complexType>
</xs:element>
	
<xs:element name="methodSet">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="method" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
</xs:element>
	
<xs:element name="implementedInterfaceSet">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="interface" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="classSet">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="class"   minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
</xs:element>	

<xs:element name="fileSet">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="file" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
</xs:element>	
	
<!--===============================-->
<!-- Definition of complex element -->
<!--===============================-->

<xs:element name="dir">
	<xs:complexType>
		<xs:attribute ref="name" use="required" />
		<xs:attribute ref="descriptionFile" use="required" />
	</xs:complexType>
</xs:element>
	
<xs:element name="import">
	<xs:complexType>
		<xs:attribute ref="value" use="required" />
	</xs:complexType>
</xs:element>		
	
<xs:element name="parameter">
	<xs:complexType>
		<xs:attribute ref="name" use="required" />
		<xs:attribute ref="type" use="required" />
		<xs:attribute ref="modifier" use="required" />
	</xs:complexType>
</xs:element>	
	
<xs:element name="attribute">
	<xs:complexType>
		<xs:attribute ref="name" use="required" />
		<xs:attribute ref="type" use="required" />
		<xs:attribute ref="modifier" use="required" />
	</xs:complexType>
</xs:element>	

<xs:element name="method">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="parameterSet" />
		</xs:sequence>
		<xs:attribute ref="name" use="required" />
		<xs:attribute ref="returnType" use="required" />
		<xs:attribute ref="modifier" use="required" />
	</xs:complexType>
</xs:element>


<xs:element name="interface">
	<xs:complexType>
		<xs:attribute ref="name" use="required" />
	</xs:complexType>
</xs:element>
	
<xs:element name="class">
<xs:complexType>
		<xs:sequence>
			<xs:element ref="implementedInterfaceSet" />
			<xs:element ref="attributeSet" />				
			<xs:element ref="methodSet" />
		</xs:sequence>
		<xs:attribute ref="name" use="required" />
	    <xs:attribute ref="package" use="required" />
		<xs:attribute ref="modifier" use="required" />
		<xs:attribute ref="parentClass" use="required" />
</xs:complexType>	
</xs:element>
	
<xs:element name="file">
<xs:complexType>
		<xs:sequence>
			<xs:element ref="importSet" />				
			<xs:element ref="classSet" />
		</xs:sequence>
		<xs:attribute ref="name" use="required" />
	    <xs:attribute ref="absolutePath" use="required" />
</xs:complexType>	
</xs:element>
	
<xs:element name="directory">
<xs:complexType>
		<xs:sequence>
			<xs:element ref="directorySet" />				
			<xs:element ref="fileSet" />
		</xs:sequence>
		<xs:attribute ref="name" use="required" />
	    <xs:attribute ref="absolutePath" use="required" />
</xs:complexType>	
</xs:element>

</xs:schema>

=== damiencuvillier/codesquale/CodeSquale/test/classpath.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<directory xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DirectoryFile.xsd" absolutePath="@value" name="classpath">
<directorySet/>
<fileSet>
<file name="BshClassLoader.java">
<importSet>
<import value="java.net."/>
<import value="java.util."/>
<import value="java.io."/>
<import value="bsh"/>
</importSet>
<classSet>
<class name="BshClassLoader" package="bsh.classpath." parentClass="URLClassLoader" modifier="public">
<implementedInterfaceSet/>
<attributeSet>
<attribute name="BshClassManager" type="BshClassManager" modifier=""/>
</attributeSet>
<methodSet>
<method name="addURL" returnType="" modifier=""/>
<method name="loadClass" returnType="Class" modifier=""/>
<method name="findClass" returnType="Class" modifier=""/>
<method name="getClassManager" returnType="BshClassManager" modifier=""/>
</methodSet>
</class>
</classSet>
</file>
<file name="BshClassPath.java">
<importSet>
<import value="java.util."/>
<import value="zip."/>
<import value="java.io."/>
<import value="java.net."/>
<import value="java.io.File"/>
<import value="bsh"/>
<import value="bsh"/>
<import value="bsh"/>
<import value="ref.WeakReference"/>
<import value="bsh"/>
</importSet>
<classSet>
<class name="BshClassPath" package="bsh.classpath." parentClass="" modifier="public">
<implementedInterfaceSet>
<interface name="ClassPathListener"/>
<interface name="NameSource"/>
</implementedInterfaceSet>
<attributeSet>
<attribute name="String" type="String" modifier=""/>
<attribute name="List" type="List" modifier="private"/>
<attribute name="List" type="List" modifier="private"/>
<attribute name="Map" type="Map" modifier="private"/>
<attribute name="Map" type="Map" modifier="private"/>
<attribute name="" type="boolean" modifier="private"/>
<attribute name="UnqualifiedNameTable" type="UnqualifiedNameTable" modifier="private"/>
<attribute name="" type="boolean" modifier="private"/>
<attribute name="Vector" type="Vector" modifier=""/>
<attribute name="" type="[" modifier="static"/>
<attribute name="BshClassPath" type="BshClassPath" modifier="static"/>
<attribute name="BshClassPath" type="BshClassPath" modifier="static"/>
<attribute name="List" type="List" modifier=""/>
<attribute name="MappingFeedback" type="MappingFeedback" modifier="static"/>
</attributeSet>
<methodSet>
<method name="setPath" returnType="" modifier=""/>
<method name="addComponent" returnType="" modifier=""/>
<method name="add" returnType="" modifier=""/>
<method name="add" returnType="" modifier=""/>
<method name="getPathComponents" returnType="" modifier=""/>
<method name="getClassesForPackage" returnType="Set" modifier=""/>
<method name="getClassSource" returnType="ClassSource" modifier=""/>
<method name="setClassSource" returnType="" modifier=""/>
<method name="insureInitialized" returnType="" modifier=""/>
<method name="insureInitialized" returnType="" modifier=""/>
<method name="getFullPath" returnType="List" modifier=""/>
<method name="getClassNameByUnqName" returnType="String" modifier=""/>
<method name="getUnqualifiedNameTable" returnType="UnqualifiedNameTable" modifier=""/>
<method name="buildUnqualifiedNameTable" returnType="UnqualifiedNameTable" modifier=""/>
<method name="getAllNames" returnType="" modifier=""/>
<method name="map" returnType="" modifier=""/>
<method name="map" returnType="" modifier=""/>
<method name="map" returnType="" modifier=""/>
<method name="mapClass" returnType="" modifier=""/>
<method name="reset" returnType="" modifier=""/>
<method name="clearCachedStructures" returnType="" modifier=""/>
<method name="classPathChanged" returnType="" modifier=""/>
<method name="traverseDirForClasses" returnType="" modifier=""/>
<method name="traverseDirForClassesAux" returnType="List" modifier=""/>
<method name="searchJarForClasses" returnType="" modifier=""/>
<method name="isClassFileName" returnType="" modifier=""/>
<method name="isArchiveFileName" returnType="" modifier=""/>
<method name="canonicalizeClassName" returnType="String" modifier=""/>
<method name="splitClassname" returnType="" modifier=""/>
<method name="removeInnerClassNames" returnType="Collection" modifier=""/>
<method name="getUserClassPathComponents" returnType="" modifier=""/>
<method name="getPackagesSet" returnType="Set" modifier=""/>
<method name="addListener" returnType="" modifier=""/>
<method name="removeListener" returnType="" modifier=""/>
<method name="notifyListeners" returnType="" modifier=""/>
<method name="getUserClassPath" returnType="BshClassPath" modifier=""/>
<method name="getBootClassPath" returnType="BshClassPath" modifier=""/>
<method name="getRTJarPath" returnType="String" modifier=""/>
<method name="main" returnType="" modifier=""/>
<method name="toString" returnType="String" modifier=""/>
<method name="nameSpaceChanged" returnType="" modifier=""/>
<method name="addNameSourceListener" returnType="" modifier=""/>
<method name="addMappingFeedback" returnType="" modifier=""/>
<method name="startClassMapping" returnType="" modifier=""/>
<method name="classMapping" returnType="" modifier=""/>
<method name="errorWhileMapping" returnType="" modifier=""/>
<method name="endClassMapping" returnType="" modifier=""/>
</methodSet>
</class>
</classSet>
</file>
<file name="ClassManagerImpl.java">
<importSet>
<import value="java.net."/>
<import value="java.util."/>
<import value="ref."/>
<import value="java.io.IOException"/>
<import value="java.io."/>
<import value="BshClassPath.ClassSource"/>
<import value="BshClassPath.JarClassSource"/>
<import value="BshClassPath.GeneratedClassSource"/>
<import value="bsh"/>
<import value="bsh"/>
<import value="bsh"/>
<import value="bsh"/>
</importSet>
<classSet>
<class name="ClassManagerImpl" package="bsh.classpath." parentClass="BshClassManager" modifier="public">
<implementedInterfaceSet/>
<attributeSet>
<attribute name="String" type="String" modifier="static"/>
<attribute name="BshClassPath" type="BshClassPath" modifier="private"/>
<attribute name="" type="boolean" modifier="private"/>
<attribute name="BshClassPath" type="BshClassPath" modifier="private"/>
<attribute name="Vector" type="Vector" modifier="private"/>
<attribute name="ReferenceQueue" type="ReferenceQueue" modifier="private"/>
<attribute name="BshClassLoader" type="BshClassLoader" modifier="private"/>
<attribute name="Map" type="Map" modifier="private"/>
</attributeSet>
<methodSet>
<method name="classForName" returnType="Class" modifier=""/>
<method name="getResource" returnType="URL" modifier=""/>
<method name="getResourceAsStream" returnType="InputStream" modifier=""/>
<method name="getLoaderForClass" returnType="ClassLoader" modifier=""/>
<method name="addClassPath" returnType="" modifier=""/>
<method name="reset" returnType="" modifier=""/>
<method name="setClassPath" returnType="" modifier=""/>
<method name="reloadAllClasses" returnType="" modifier=""/>
<method name="initBaseLoader" returnType="" modifier=""/>
<method name="reloadClasses" returnType="" modifier=""/>
<method name="reloadPackage" returnType="" modifier=""/>
<method name="getClassPath" returnType="BshClassPath" modifier=""/>
<method name="doSuperImport" returnType="" modifier=""/>
<method name="hasSuperImport" returnType="" modifier=""/>
<method name="getClassNameByUnqName" returnType="String" modifier=""/>
<method name="addListener" returnType="" modifier=""/>
<method name="removeListener" returnType="" modifier=""/>
<method name="getBaseLoader" returnType="ClassLoader" modifier=""/>
<method name="defineClass" returnType="Class" modifier=""/>
<method name="classLoaderChanged" returnType="" modifier=""/>
<method name="dump" returnType="" modifier=""/>
</methodSet>
</class>
</classSet>
</file>
<file name="ClassPathListener.java">
<importSet/>
<classSet/>
</file>
<file name="DiscreteFilesClassLoader.java">
<importSet>
<import value="java.io."/>
<import value="java.io.File"/>
<import value="java.util."/>
<import value="java.awt."/>
<import value="bsh"/>
<import value="BshClassPath.ClassSource"/>
<import value="BshClassPath.DirClassSource"/>
<import value="BshClassPath.GeneratedClassSource"/>
</importSet>
<classSet>
<class name="DiscreteFilesClassLoader" package="bsh.classpath." parentClass="BshClassLoader" modifier="public">
<implementedInterfaceSet/>
<attributeSet>
<attribute name="ClassSourceMap" type="ClassSourceMap" modifier=""/>
</attributeSet>
<methodSet>
<method name="findClass" returnType="Class" modifier=""/>
<method name="toString" returnType="String" modifier=""/>
</methodSet>
</class>
</classSet>
</file>
</fileSet>
</directory>

=== damiencuvillier/codesquale/CodeSquale/xml/models/DirectoryFile.xml
<?xml version="1.0" encoding="UTF-8"?><!-- Describes a directory with his content 	Content :		- DirectorySet : directories list		- fileSet : files list		Each File is described with the following details :	- Classes list	- Package	- Imports ...		Please read the official documentation to obtain more details--><directory absolutePath="" name="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../XSD Schemas/DirectoryFile.xsd">	<directorySet>		<dir name="" descriptionFile=""/>	</directorySet>	<fileSet>		<file name="" absolutePath="">			<importSet>				<import value=""/>				<import value=""/>			</importSet>			<classSet>				<class name="" package="" modifier="" parentClass="">
				<!-- TODO Changer les modifiers en static=false|true final=false|true et visibility="" -->
					<implementedInterfaceSet>
						<interface name="" />
					</implementedInterfaceSet>					<attributeSet>						<attribute name="" type="" modifier=""/>
						<!-- TODO Changer les modifiers en static=false|true final=false|true et visibility="" -->					</attributeSet>					<methodSet>						<method name="" returnType="" modifier="">							<parameterSet>								<parameter name="" type="" modifier=""/>							</parameterSet>						</method>					</methodSet>				</class>			</classSet>		</file>	</fileSet></directory>

=== damiencuvillier/codesquale/trunk/CodeSquale/xml/models/DirectoryFile_Sample.xml
<?xml version="1.0" encoding="UTF-8"?><!-- Describes a directory with his content 	Content :		- DirectorySet : directories list		- fileSet : files list		Each File is described with the following details :	- Classes list	- Package	- Imports ...		Please read the official documentation to obtain more details--><directory absolutePath="/src/sampleTestProject/" name="sampleProject" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/xml/XSD Schemas/DirectoryFile.xsd">		<directorySet>		<dir name="sample1" descriptionFile="This is the description of the sample directory sample1"/>		<dir name="sample2" descriptionFile="This is the description of the sample directory sample2"/>		<dir name="otherSample" descriptionFile="Another description of a sample Directory"/>	</directorySet>			<fileSet>				<file name="sampleClass1.java" absolutePath="/src/sampleTestProject/sampleClass1.java">						<importSet>				<import value="java.util"/>				<import value="java.lang"/>			</importSet>			<classSet>				<class name="SampleClass1" package="samplePackage" modifier="public" parentClass="">
				<!-- TODO Changer les modifiers en static=false|true final=false|true et visibility="" -->
					<implementedInterfaceSet>
						<interface name="ISampleInterface1" />						<interface name="ISampleInterface2" />
					</implementedInterfaceSet>					<attributeSet>						<attribute name="attribute1" type="int" modifier="private"/>						<attribute name="attribute2" type="string" modifier="private"/>
						<!-- TODO Changer les modifiers en static=false|true final=false|true et visibility="" -->					</attributeSet>					<methodSet>						<method name="MethodA" returnType="void" modifier="public">							<parameterSet>								<parameter name="param1" type="string" modifier=""/>							</parameterSet>						</method>						<method name="MethodB" returnType="int" modifier="public" />					</methodSet>				</class>								<class name="SampleClass2" package="samplePackage2" modifier="private" parentClass="">				<!-- TODO Changer les modifiers en static=false|true final=false|true et visibility="" -->					<implementedInterfaceSet>						<interface name="ISampleInterface2" />					</implementedInterfaceSet>					<attributeSet>						<attribute name="attribute1" type="int" modifier="private"/>						<!-- TODO Changer les modifiers en static=false|true final=false|true et visibility="" -->					</attributeSet>					<methodSet>						<method name="MethodC" returnType="void" modifier="public" />						<method name="MethodD" returnType="int" modifier="public" />					</methodSet>				</class>			</classSet>			</file>				<file name="sampleClass2.java" absolutePath="/src/sampleTestProject/sampleClass1.java">						<importSet>				<import value="java.util"/>				<import value="java.lang"/>			</importSet>			<classSet>				<class name="SampleClass2" package="samplePackage" modifier="public" parentClass="">				<!-- TODO Changer les modifiers en static=false|true final=false|true et visibility="" -->					<implementedInterfaceSet>						<interface name="ISampleInterface1" />						<interface name="ISampleInterface2" />					</implementedInterfaceSet>					<attributeSet>						<attribute name="attribute1" type="int" modifier="private"/>						<attribute name="attribute2" type="string" modifier="private"/>						<!-- TODO Changer les modifiers en static=false|true final=false|true et visibility="" -->					</attributeSet>					<methodSet>						<method name="MethodA" returnType="void" modifier="public">							<parameterSet>								<parameter name="param1" type="string" modifier=""/>							</parameterSet>						</method>						<method name="MethodB" returnType="int" modifier="public" />					</methodSet>				</class>								<class name="SampleClass2" package="samplePackage2" modifier="public" parentClass="">				<!-- TODO Changer les modifiers en static=false|true final=false|true et visibility="" -->					<implementedInterfaceSet>						<interface name="ISampleInterface2" />					</implementedInterfaceSet>					<attributeSet>						<attribute name="attribute1" type="int" modifier="private"/>						<!-- TODO Changer les modifiers en static=false|true final=false|true et visibility="" -->					</attributeSet>					<methodSet>						<method name="MethodC" returnType="void" modifier="public" />						<method name="MethodD" returnType="int" modifier="public" />					</methodSet>				</class>			</classSet>			</file>			</fileSet></directory>
